name: documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install meson libglib2.0-dev libyaml-dev libparted-dev \
                               doxygen python3 python3-virtualenv
      - name: Build documentation
        run: |
          virtualenv -p /usr/bin/python3 -v env
          source env/bin/activate
          pip install -r doc/requirements.txt
          meson build -Ddoc=true
          ninja -C build doc/html
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/doc/html
